"""Emit `life.shdl`: a W x H toroidal Conway's Game of Life grid of Cells.

Every cell is wired to its eight wrap-around neighbours.  State is exposed
as one output port per row (Q1..QH, each W bits) and seeded through one
input port per row (S1..SH), keeping every port within the 64-bit ABI
ceiling.  Load/Phi1/Phi2 are scalar controls shared by the whole grid.
"""
from __future__ import annotations

import sys

# eight neighbour offsets (row, col); order is irrelevant to a popcount
DELTAS = [(-1, -1), (-1, 0), (-1, 1),
          ( 0, -1),          ( 0, 1),
          ( 1, -1), ( 1, 0), ( 1, 1)]


def generate(W: int, H: int) -> str:
    seed_ports = ", ".join(f"S{r}[{W}]" for r in range(1, H + 1))
    out_ports = ", ".join(f"Q{r}[{W}]" for r in range(1, H + 1))

    lines = [
        '"""Conway\'s Game of Life -- a %dx%d toroidal grid of gate-level cells.' % (W, H),
        "Generated by gen_life.py.  One Cell per square; eight wrap-around",
        "neighbours each; B3/S23 evaluated in gates; state in master-slave",
        "flip-flops on a two-phase clock.",
        '"""',
        "",
        "use cell::{Cell};",
        "",
        f"top component Life({seed_ports}, Load, Phi1, Phi2)",
        f"    -> ({out_ports}) {{",
        "",
    ]

    # instance declarations
    for r in range(1, H + 1):
        decls = "  ".join(f"c{r}_{c}: Cell;" for c in range(1, W + 1))
        lines.append(f"    {decls}")
    lines.append("")
    lines.append("    connect {")

    for r in range(1, H + 1):
        for c in range(1, W + 1):
            inst = f"c{r}_{c}"
            conns = []
            for k, (dr, dc) in enumerate(DELTAS, start=1):
                rr = (r - 1 + dr) % H + 1
                cc = (c - 1 + dc) % W + 1
                conns.append(f"c{rr}_{cc}.Q -> {inst}.N{k};")
            conns.append(f"S{r}[{c}] -> {inst}.Seed;")
            conns.append(f"Load -> {inst}.Load;")
            conns.append(f"Phi1 -> {inst}.Phi1;")
            conns.append(f"Phi2 -> {inst}.Phi2;")
            conns.append(f"{inst}.Q -> Q{r}[{c}];")
            lines.append(f"        # cell ({r},{c})")
            lines.append("        " + " ".join(conns))
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    W = int(sys.argv[1]) if len(sys.argv) > 1 else 12
    H = int(sys.argv[2]) if len(sys.argv) > 2 else 12
    out = sys.argv[3] if len(sys.argv) > 3 else "life.shdl"
    with open(out, "w") as f:
        f.write(generate(W, H))
    print(f"wrote {out}: {W}x{H} grid ({W * H} cells)")
